# Site settings
title:          "Travel"
description:    "Tales from my time in the outdoors."
baseurl:        ""
url:            "https://travel.abhishekbalam.xyz/"

# Author
author:
  name:         Abhishek Balam
  url:          https://abhishekbalam.xyz
  email:        abhishekbalam96@gmail.com

# Build settings
markdown: kramdown

permalink: /:title

# Build settings
port: 4000

