
title: Travel Blog
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A blog of all my treks and travels.

baseurl: "" # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
